'use client'

import { Button } from '@/components/ui/button'

type MenuItem = { id: string; nameEn: string; nameAr: string; descriptionEn?: string; descriptionAr?: string; category: string; price: string; prepHours: number; available: boolean; imageUrl?: string }
type Draft = { name_en: string; name_ar: string; description_en: string; description_ar: string; category: string; price: string; prep_hours: string; image_url: string; available: boolean }
export function MenuEditor({ menu, draft, editing, loading, onDraft, onSave, onNew, onEdit, onDisable, onDelete, onReenable }: { menu: MenuItem[]; draft: Draft; editing: string | null; loading: boolean; onDraft: (draft: Draft) => void; onSave: (event: React.FormEvent) => void; onNew: () => void; onEdit: (item: MenuItem) => void; onDisable: (item: MenuItem) => void; onDelete: (item: MenuItem) => void; onReenable: (item: MenuItem) => void }) {
  const fields: [keyof Draft, string][] = [['name_en','English name'],['name_ar','Arabic name'],['description_en','English description'],['description_ar','Arabic description'],['category','Category'],['price','Price'],['prep_hours','Prep hours'],['image_url','Image URL']]
  return <section className="admin-panel"><div className="admin-toolbar"><div><p className="eyebrow">Menu editor</p><h2>{editing ? 'Edit item' : 'Add menu item'}</h2></div><Button variant="outline" onClick={onNew}>New item</Button></div><form className="menu-editor-form" onSubmit={onSave}>{fields.map(([key, label]) => <label key={key}>{label}<input dir={key.endsWith('_ar') ? 'rtl' : 'ltr'} required={['name_en','name_ar','category','price','prep_hours'].includes(key)} value={draft[key] as string} onChange={(event) => onDraft({ ...draft, [key]: event.target.value })} /></label>)}<label><span>Available</span><input type="checkbox" checked={draft.available} onChange={(event) => onDraft({ ...draft, available: event.target.checked })} /></label><Button type="submit">{editing ? 'Save changes' : 'Add item'}</Button></form>{loading && <p className="notice" aria-live="polite">Loading menu…</p>}<div className="menu-editor-list">{menu.map((item) => <article className={`menu-editor-row${item.available ? '' : ' disabled'}`} key={item.id}><div><strong>{item.nameEn}</strong><span dir="rtl">{item.nameAr}</span><small>{item.category} · ${item.price} · {item.available ? 'Available' : 'Disabled'}</small><small>{item.descriptionEn}</small><small dir="rtl">{item.descriptionAr}</small></div><div><Button variant="outline" onClick={() => onEdit(item)}>Edit</Button>{item.available ? <span><Button variant="outline" onClick={() => onDisable(item)}>Disable</Button><Button variant="destructive" onClick={() => onDelete(item)}>Delete</Button></span> : <Button variant="outline" onClick={() => void onReenable(item)}>Re-enable</Button>}</div></article>)}</div></section>
}
export type { MenuItem, Draft }
