'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'

export type Order = { id: string; order_number: string; customer_name: string; customer_phone: string; delivery_address: string | null; fulfillment: string; ready_date: string; total: string; payment_status: string; payment_reference: string | null; payment_proof_url: string | null; deposit_paid: boolean; balance_paid: boolean; status: string; created_at: string; verified_by: string | null; verified_at: string | null; verified_by_name: string | null }

type Props = { orders: Order[]; filtered: Order[]; pendingIds: Set<string>; paymentsOnly: boolean; search: string; status: string; fulfillment: string; payment: string; statuses: string[]; payments: string[]; onSearch: (value: string) => void; onStatus: (value: string) => void; onFulfillment: (value: string) => void; onPayment: (value: string) => void; onExpand: (order: Order) => void; onPatch: (id: string, patch: Record<string, unknown>) => void; onPreview: (url: string) => void; offset: number; pageSize: number }

export function OrderTable({ orders, filtered, pendingIds, paymentsOnly, search, status, fulfillment, payment, statuses, payments, onSearch, onStatus, onFulfillment, onPayment, onExpand, onPatch, onPreview, offset, pageSize }: Props) {
  const rows = paymentsOnly ? filtered.filter((order) => pendingIds.has(order.id)) : filtered
  const [references, setReferences] = useState<Record<string, string>>({})
  return <>
    <div className="admin-toolbar"><div><p className="eyebrow">{paymentsOnly ? 'Verification queue' : 'Order management'}</p><h2>{paymentsOnly ? 'Unpaid and partially paid' : 'Orders'}</h2></div><div className="admin-filters"><input className="field" placeholder="Search order, name, phone" value={search} onChange={(event) => onSearch(event.target.value)} /><select className="field" value={status} onChange={(event) => onStatus(event.target.value)}><option value="all">All statuses</option>{statuses.map((value) => <option key={value}>{value}</option>)}</select><select className="field" value={fulfillment} onChange={(event) => onFulfillment(event.target.value)}><option value="all">All fulfillment</option><option>delivery</option><option>pickup</option></select><select className="field" value={payment} onChange={(event) => onPayment(event.target.value)}><option value="all">All payments</option>{payments.map((value) => <option key={value}>{value}</option>)}</select></div></div>
    <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Fulfillment</th><th>Date</th><th>Total</th><th>Status</th><th>Payment</th><th>Controls</th></tr></thead><tbody>{rows.map((order) => { const reference = references[order.id] ?? order.payment_reference ?? ''; return <tr key={order.id}><td><Button variant="link" onClick={() => onExpand(order)}>{order.order_number}</Button><small>{order.created_at}</small></td><td>{order.customer_name}<small>{order.customer_phone}</small><small>{order.delivery_address || 'Pickup'}</small></td><td>{order.fulfillment}</td><td>{order.ready_date}</td><td>${Number(order.total).toFixed(2)}</td><td><select className="field" value={order.status} onChange={(event) => { const next = event.target.value; if (next === 'cancelled' && !window.confirm('Cancel this order?')) return; onPatch(order.id, { status: next }) }}>{statuses.map((value) => <option key={value}>{value}</option>)}</select></td><td><select className="field" value={order.payment_status} onChange={(event) => onPatch(order.id, { paymentStatus: event.target.value })}>{payments.map((value) => <option key={value}>{value}</option>)}</select><input className="field" aria-label={`Payment reference for ${order.order_number}`} value={reference} onChange={(event) => setReferences((current) => ({ ...current, [order.id]: event.target.value }))} onBlur={(event) => { const value = event.target.value; if (value !== (order.payment_reference ?? '')) onPatch(order.id, { paymentReference: value }) }} />{order.payment_proof_url && <button type="button" className="proof-thumb-button" onClick={() => onPreview(order.payment_proof_url!)}><img className="proof-thumb" src={order.payment_proof_url} alt="Payment proof thumbnail" /></button>}{order.verified_at && <small>Verified by {order.verified_by_name || order.verified_by || 'admin'} · {new Date(order.verified_at).toLocaleString()}</small>}</td><td><Button variant="outline" onClick={() => onPatch(order.id, { depositPaid: !order.deposit_paid })}>{order.deposit_paid ? 'Deposit paid' : 'Mark deposit'}</Button><Button variant="outline" onClick={() => onPatch(order.id, { balancePaid: !order.balance_paid })}>{order.balance_paid ? 'Balance paid' : 'Mark balance'}</Button></td></tr> })}</tbody></table></div><div className="admin-pagination"><Button variant="outline" disabled={offset === 0} onClick={() => window.location.assign(`/admin?offset=${Math.max(0, offset - pageSize)}`)}>Previous</Button><span>Showing {offset + 1}–{offset + rows.length}</span><Button variant="outline" disabled={rows.length < pageSize} onClick={() => window.location.assign(`/admin?offset=${offset + pageSize}`)}>Load more</Button></div>
  </>
}
